import {
  BookingListing,
  BookingCategory,
  HeroSlide,
  TrendingDestination,
  FeaturedHost,
  GuestReview,
  BookingFeature,
} from './booking.models';

export const HERO_SLIDES: HeroSlide[] = [
  {
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1920&h=800&fit=crop',
    titleKey: 'booking.hero.slides.0.title',
    subtitleKey: 'booking.hero.slides.0.subtitle',
    buttonKey: 'booking.hero.slides.0.button',
  },
  {
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1920&h=800&fit=crop',
    titleKey: 'booking.hero.slides.1.title',
    subtitleKey: 'booking.hero.slides.1.subtitle',
    buttonKey: 'booking.hero.slides.1.button',
  },
  {
    image: 'https://images.unsplash.com/photo-1511882150382-421056c89033?w=1920&h=800&fit=crop',
    titleKey: 'booking.hero.slides.2.title',
    subtitleKey: 'booking.hero.slides.2.subtitle',
    buttonKey: 'booking.hero.slides.2.button',
  },
];

export const BOOKING_CATEGORIES: BookingCategory[] = [
  { nameKey: 'booking.categories.all', icon: 'home' },
  { nameKey: 'booking.categories.restaurants', icon: 'restaurant' },
  { nameKey: 'booking.categories.hotels', icon: 'hotel' },
  { nameKey: 'booking.categories.gaming', icon: 'sports_esports' },
  { nameKey: 'booking.categories.cafes', icon: 'local_cafe' },
  { nameKey: 'booking.categories.gyms', icon: 'fitness_center' },
  { nameKey: 'booking.categories.beauty', icon: 'spa' },
];

export const TRENDING_DESTINATIONS: TrendingDestination[] = [
  {
    nameKey: 'booking.trending.destinations.0.name',
    count: 234,
    image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=300&fit=crop',
    trend: '+23%',
  },
  {
    nameKey: 'booking.trending.destinations.1.name',
    count: 156,
    image: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=400&h=300&fit=crop',
    trend: '+18%',
  },
  {
    nameKey: 'booking.trending.destinations.2.name',
    count: 189,
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400&h=300&fit=crop',
    trend: '+31%',
  },
  {
    nameKey: 'booking.trending.destinations.3.name',
    count: 127,
    image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=400&h=300&fit=crop',
    trend: '+15%',
  },
];

export const FEATURED_HOSTS: FeaturedHost[] = [
  {
    name: 'Maria Rodriguez',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    venue: 'Sunset Bistro',
    rating: 4.98,
    reviews: 432,
    verified: true,
  },
  {
    name: 'James Chen',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    venue: 'GameZone Arena',
    rating: 4.95,
    reviews: 378,
    verified: true,
  },
  {
    name: 'Sophie Laurent',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    venue: 'Luxury Suites Hotel',
    rating: 4.97,
    reviews: 501,
    verified: true,
  },
];

export const GUEST_REVIEWS: GuestReview[] = [
  {
    user: 'Alex Thompson',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
    rating: 5,
    textKey: 'booking.reviews.items.0.text',
    venueKey: 'booking.reviews.items.0.venue',
    dateKey: 'booking.reviews.items.0.date',
  },
  {
    user: 'Emma Wilson',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop',
    rating: 5,
    textKey: 'booking.reviews.items.1.text',
    venueKey: 'booking.reviews.items.1.venue',
    dateKey: 'booking.reviews.items.1.date',
  },
  {
    user: 'Michael Brown',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
    rating: 5,
    textKey: 'booking.reviews.items.2.text',
    venueKey: 'booking.reviews.items.2.venue',
    dateKey: 'booking.reviews.items.2.date',
  },
];

export const BOOKING_LISTINGS: BookingListing[] = [
  {
    id: '1',
    title: 'Luxury Downtown Restaurant & Bar',
    images: ['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop'],
    category: 'booking.categories.restaurants',
    rating: 4.9,
    reviewCount: 287,
    location: 'Downtown, San Francisco',
    distance: '3.2 miles away',
    price: 85,
    priceUnit: 'per person',
    host: 'Hosted by Maria',
    verified: true,
    featured: true,
    guests: 50,
    instantBook: true,
  },
  {
    id: '2',
    title: 'Modern Gaming Lounge & eSports Arena',
    images: ['https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=600&h=400&fit=crop'],
    category: 'booking.categories.gaming',
    rating: 4.95,
    reviewCount: 412,
    location: 'Tech District, SF',
    distance: '1.8 miles away',
    price: 25,
    priceUnit: 'per hour',
    host: 'Hosted by Alex',
    verified: true,
    guests: 30,
    instantBook: true,
  },
  {
    id: '3',
    title: 'Boutique Hotel in City Center',
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=400&fit=crop'],
    category: 'booking.categories.hotels',
    rating: 4.8,
    reviewCount: 523,
    location: 'City Center, SF',
    distance: '2.5 miles away',
    price: 250,
    priceUnit: 'night',
    host: 'Hosted by Grand Hotels',
    verified: true,
    beds: 2,
    guests: 4,
    instantBook: false,
  },
  {
    id: '4',
    title: 'Cozy Coffee Shop & Co-Working Space',
    images: ['https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=600&h=400&fit=crop'],
    category: 'booking.categories.cafes',
    rating: 4.7,
    reviewCount: 198,
    location: 'Marina District, SF',
    distance: '4.1 miles away',
    price: 15,
    priceUnit: 'per person',
    host: 'Hosted by Bean & Co',
    verified: true,
    guests: 25,
    instantBook: true,
  },
  {
    id: '5',
    title: 'Premium Fitness Center & Spa',
    images: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=400&fit=crop'],
    category: 'booking.categories.gyms',
    rating: 4.85,
    reviewCount: 345,
    location: 'Financial District, SF',
    distance: '2.9 miles away',
    price: 45,
    priceUnit: 'per day',
    host: 'Hosted by FitLife',
    verified: true,
    guests: 100,
    instantBook: true,
  },
  {
    id: '6',
    title: 'Waterfront Seafood Restaurant',
    images: ['https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&h=400&fit=crop'],
    category: 'booking.categories.restaurants',
    rating: 4.92,
    reviewCount: 456,
    location: "Fisherman's Wharf, SF",
    distance: '5.2 miles away',
    price: 95,
    priceUnit: 'per person',
    host: 'Hosted by Ocean View',
    verified: true,
    guests: 80,
    instantBook: true,
  },
  {
    id: '7',
    title: 'VR Gaming Experience Center',
    images: ['https://images.unsplash.com/photo-1617802690658-1173a812650d?w=600&h=400&fit=crop'],
    category: 'booking.categories.gaming',
    rating: 4.88,
    reviewCount: 234,
    location: 'SOMA, SF',
    distance: '1.2 miles away',
    price: 35,
    priceUnit: 'per hour',
    host: 'Hosted by VR World',
    verified: true,
    guests: 20,
    instantBook: false,
  },
  {
    id: '8',
    title: 'Historic Luxury Hotel & Suites',
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&h=400&fit=crop'],
    category: 'booking.categories.hotels',
    rating: 4.95,
    reviewCount: 678,
    location: 'Nob Hill, SF',
    distance: '3.7 miles away',
    price: 450,
    priceUnit: 'night',
    host: 'Hosted by Heritage Hotels',
    verified: true,
    beds: 1,
    guests: 2,
    instantBook: true,
  },
];

export const BOOKING_FEATURES: BookingFeature[] = [
  { icon: 'bolt', titleKey: 'booking.features.instant.title', descriptionKey: 'booking.features.instant.description' },
  { icon: 'verified_user', titleKey: 'booking.features.verified.title', descriptionKey: 'booking.features.verified.description' },
  { icon: 'emoji_events', titleKey: 'booking.features.price.title', descriptionKey: 'booking.features.price.description' },
  { icon: 'schedule', titleKey: 'booking.features.support.title', descriptionKey: 'booking.features.support.description' },
];
