export const formInputErrors: Record<string, string> = {
  required: 'ველი სავალდებულოა',
  email: 'შეიყვანე სწორად ფორმატირებული ელფოსტა',
  minlength: 'მოკლეა, მინიმუმ {n} სიმბოლო',
  maxlength: 'გრძელია, მაქსიმუმ {n} სიმბოლო',
  emptySpace: 'ცარიელი სივრცე არ შეიძლება',
  mustMatchField: 'პაროლები არ ემთხვევა',
  server: 'ეს ელფოსტა უკვე გამოყენებულია',
  serverDown: 'სცადე მოგვიანებით',
  verificationFailed: 'ვერიფიკაციის კოდს დრო გაუვიდა ან არასწორია',
  codeExpired: 'ვერიფიკაციის კოდს დრო გაუვიდა',
  incorrectCode: 'ვერიფიკაციის კოდი არასწორია',
  invalidCredentials: 'ელფოსტა ან პაროლი არასწორია',
  notVerified: 'გთხოვთ დაადასტუროთ ელფოსტა',
  userNotFound: 'ამ მეილით დარეგისტრირებული პროფილი არ მოიძებნა',
  rateLimitExceeded: 'კოდის ხელახლა მისაღებად გთხოვთ მოიცადოთ 2 წუთი',

  resetSent: 'თუ ეს იმეილი არსებობს, reset ლინკი გაიგზავნა',
  resetFailed: 'პაროლის შეცვლა ვერ მოხერხდა',

  edgeSpaces: 'პაროლი არ უნდა იწყებოდეს ან მთავრდებოდეს სფეისით',
  passwordStrengthDigit: 'უნდა შეიცავდეს მინიმუმ 1 ციფრს',
  passwordStrengthMinLength: 'მინიმუმ 8 სიმბოლო',
  passwordStrengthUppercase: 'უნდა შეიცავდეს მინიმუმ 1 დიდ ასოს',
  passwordStrengthLowercase: 'უნდა შეიცავდეს მინიმუმ 1 პატარა ასოს',
  passwordStrengthSpecialChar: 'უნდა შეიცავდეს მინიმუმ 1 სპეციალურ სიმბოლოს',

  alreadyRegistered: 'ეს ელფოსტა უკვე რეგისტრირებულია',
  passwordsSame: 'ახალი პაროლი არ უნდა ემთხვეოდეს ძველ პაროლს',
};